In [2]:
#Numpy è una libreria che fornisce un array multidimensionale. Esso si può usare ad esempio per memorizzare le immagini in numeri
#oppure esso è molto usato per manipolare e lavorare con i valori all'interno dell'array
#La libreria numpy, viene usata da molte altre librerie come: Pandas oppure openCV (la quale gestisce le immagini)
import numpy
#Documentazione: https://numpy.org/doc/

In [3]:
n=numpy.arange(27)

In [4]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
#questo era un semplice vettore di numeri fino a 27, se vogliamo poi passare ad una matrice bisogna fare un reshape
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [6]:
#oppure tridimensionale 
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
#per convertire un oggetto ad un array si può utilizzare la funzione
m = numpy.asarray([10,15])
m

array([10, 15])

In [8]:
#adesso andiamo a importare la libreria che serve per la gestire le immagini: 
import cv2
#Documentazione: https://opencv.org/

In [9]:
#per leggere un immagine in py, bisogna usare il metodo imread esso va a leggere l'imamgine in:
#0--> in scala di grigi
#1--> BGR blu, verde e rosso (uguale a RGB solamente che proprietario cv2)
#l'immagine presa in test è molto piccola: al massimo 15pixel per evitare grandi mole di dati
img_grey=cv2.imread("img/smallgray.png",0)
img_grey
#il risultato è una matrice numpy con 3X5 colonne --> 15px

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [10]:
img_BGR = cv2.imread("img/smallgray.png",1)
img_BGR
#il primo array è per il blu, poi il verde e poi il rosso
#matrice tridimensionale

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [11]:
#per creare delle immagini invece si usa il metodo imwrite, che permette di passare il nome dell'immagine e la matrice di valori
cv2.imwrite("newImageGray.png",img_BGR)

True

In [12]:
#per quanto riguarda l'indicizzazione e lo slice:
img_grey[0:2,2:4]
#il primo indice è per le righe (quindi richiedo le prime 2)
#il secondo indice è per le colonne (quindi richiedo dalla 2 alla 4 --> escluso)

array([[104, 121],
       [255, 255]], dtype=uint8)

In [14]:
img_grey[0,2]

104

In [17]:
#per iterare degli array si può usare il for
#PRIMO CASO: vado ad iterare per singola riga
for i in img_grey:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [18]:
#SECONDO CASO: vado ad iterare per singolo item nella matrice
for i in img_grey.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [22]:
#per andare invece a concatenare degli array bisogna usare hstack (per la concatenazione orizzontale)
#bisogna passare per forza una tupla, siccome la funzione richiede un solo parametro
#i vettori passati devono avere per forza la stessa dimensione 
new_array = numpy.hstack((img_grey, img_grey))
new_array

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [24]:
#per la concatenazione verticale si utilizza: vstack
new_array = numpy.vstack((img_grey, img_grey))
new_array

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [26]:
#per lo split di array si gestisce allo stesso modo con: vsplit e hsplit
#ricordo che non si può splittare per un numero cui divisione con il numero di elementi orizzontali o verticali da resto
#VERTICALE:
lst = numpy.vsplit(new_array,3)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [29]:
#ORIZZONTALE:
lst = numpy.hsplit(new_array,5)
print(lst)

[array([[187],
       [198],
       [209],
       [187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134],
       [158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255],
       [104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182],
       [143],
       [147],
       [182]], dtype=uint8)]
